void-linux/void-packages@master:
  BRANCH_PREFIX: void
    - .dockerignore
    - .editorconfig
    - .gitattributes
    - .github
    - .gitignore
    - .mailmap
    - CONTRIBUTING.md
    - COPYING
    - Manual.md
    - README.md
    - common
    - etc
    - srcpkgs
    - xbps-src

Makrennel/hyprland-void@master:
  BRANCH_PREFIX: hyprland
    - .github
    - COPYING
    - README.md
    - common
    - scripts
    - srcpkgs

index-0/librewolf-void@master:
  BRANCH_PREFIX: librewolf
    - .github
    - README.md
    - srcpkgs

mobinmob/abyss-packages@main:
  BRANCH_PREFIX: abyss
    - AppImageLauncher/
    - Webex/
    - adw-gtk3/
    - base16-geany-git/
    - base16-xfce4-terminal-git/
    - basilisk-beta/
    - betterbird/
    - brave-browser/
    - cudatext/
    - duplicati-beta-bin/
    - easybashgui/
    - fasd/
    - flat-remix-gtk/
    - font-JetBrainsMono/
    - font-cascadia-code-ttf/
    - font-mgopen-ttf/
    - fopnu/
    - geany-themes-git/
    - gtkgreet-git/
    - materia-theme/
    - microsoft-edge-stable/
    - moksha/
    - nano-syntax-highlighting/
    - palemoon/
    - proggyfonts/
    - quickemu/
    - rmpc/
    - seamonkey/
    - smartgit/
    - softmaker-freeoffice-2018/
    - softmaker-freeoffice-2021/
    - softmaker-freeoffice-2024/
    - soulseekqt-bin/
    - teamviewer/
    - thunderbird-bin/
    - tixati/
    - unmaintained_templates/
    - vesktop/
    - vuescan/
    - waterfox/
    - zuki-themes/
