group:
  # Lint CI workflow
  - files:
      - source: vur/
        dest: /
    repos: |
      osowoso/vur@test
      
#void-linux/void-packages@master:
#BRANCH_PREFIX: void
#Makrennel/hyprland-void@master:
#BRANCH_PREFIX: hyprland
#index-0/librewolf-void@master:
#BRANCH_PREFIX: librewolf
#mobinmob/abyss-packages@main:
#BRANCH_PREFIX: abyss
