# .github/workflows/sync.yml
name: Rebase void branch on upstream
on:
  # schedule:
    # - cron: '0 */6 * * *' # Run every 6 hours
  workflow_dispatch:   # run manually
    inputs:
      branch:
        description: "Branch to sync"
        required: true
        default: "master"
        type: string
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 9999 # greater than the number of commits you made
        ref: ${{ github.event.inputs.branch }}

    - uses: imba-tjd/rebase-upstream-action@master
      with:
        upstream: void-linux/void-packages
        branch: master
