name: Create README.md

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
  push:
    paths: .github/workflows/create-readme.yml

jobs:
  generate-repo-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get user repos
        run: |
          rm -f user_repos.json
          curl -X GET \
          https://api.github.com/users/zen0bit/repos \
          -H "Authorization: token ${{ secrets.TOKEN }}" \
          -H 'Content-Type: application/json' \
          > user_repos.json
          echo '----------------------------------'
          #cat user_repos.json
          echo '----------------------------------'

      - name: Get org repos
        run: |
          ORGANIZATIONS="AM-community OpenSourceWorldOrder oSoWoSo vb-linux voidbox-linux YourOperatingSystem"
          rm -f org_repos.json
          for org in $ORGANIZATIONS; do
            curl -X GET \
            "https://api.github.com/orgs/${org}/repos" \
            -H "Authorization: token ${{ secrets.TOKEN }}" \
            -H 'Content-Type: application/json' \
            > ${org}_repos.json
          done
          echo '----------------------------------'
          #cat org_repos.json
          echo '----------------------------------'

      - name: Generate README.md
        #if: always()
        run: |
          echo '# Included in this repository' > README.md
          echo ' * [dh](https://github.com/oSoWoSo/DistroHopper)' >> README.md
          echo ' * [distro-svg](https://github.com/oSoWoSo/distro-svg)' >> README.md
          echo ' * [github](https://github.com/oSoWoSo/.github)' >> README.md
          echo ' * [gumak](https://github.com/oSoWoSo/gumak)' >> README.md
          echo ' * [quickemu](https://github.com/oSoWoSo/quickemu)' >> README.md
          echo ' * [vbm](https://github.com/oSoWoSo/vbm)' >> README.md
          echo ' * [void-helper](https://github.com/oSoWoSo/void-helper)' >> README.md
          echo ' * [vur](https://github.com/oSoWoSo/VUR)' >> README.md
          echo ' * [wallpapers](https://github.com/oSoWoSo/Void-wallpapers)' >> README.md
          echo '' >> README.md
          echo '![Alt](https://repobeats.axiom.co/api/embed/688e53993f75a6121c9c3469c6584603208ec0ee.svg "Repobeats analytics image")' >> README.md
          echo '' >> README.md
          echo "# My Repositories" >> README.md
          echo "" >> README.md
          cat user_repos.json | jq -r '.[] | " * [\(.name)](\(.html_url))"' >> README.md
          echo '' >> README.md
          echo "# Organization Repositories" >> README.md
          echo '' >> README.md
          ORGANIZATIONS="AM-community OpenSourceWorldOrder oSoWoSo vb-linux voidbox-linux YourOperatingSystem"
          for org in $ORGANIZATIONS; do
            echo "## ${org}" >> README.md
            echo '' >> README.md
            cat ${org}_repos.json | jq -r '.[] | " * [\(.name)](\(.html_url))"' >> README.md
            echo '' >> README.md
          done

      - name: Add ⭐⭐⭐ badges
        run: |
          git pull
          while IFS= read -r line; do
            if [[ $line == "* ["* ]] && [[ $line == *") "* ]]; then
              REPO=$(echo "${line}" | grep -oP '\[\K[^]]+')
              LINE=$(echo "${line}" | cut -d' ' -f2-)
              # Possible style values: [flat, flat-square, plastic, for-the-badge, social]
              echo "* ![Stars](https://img.shields.io/github/stars/${REPO}?label=%E2%AD%90&style=plastic&logoSize=auto&labelColor=white&color=green) ${LINE}" >> new.md
            else
              echo "${line}" >> new.md
            fi
          done < README.md
          mv new.md README.md

      - name: Commit and push changes
        #if: always()
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A || echo 'Nothing to add'
          git commit -m "Update README" || echo 'Nothing to commit'
          git push origin main || echo 'Nothing to push'
