name: 🛰️
on:
  push:
    branches:
      - main
  workflow_dispatch:
  #schedule:
    #- cron: '0 */6 * * *'
  repository_dispatch:
    types: [trigger]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
env:
  GH_PAT: ${{ secrets.TOKEN }}

jobs:
  create-sync:
    name: 🛰️ sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main

      - name: DistroHopper
        run: |
          sync=dh
          syncD=DistroHopper
          branch=all
          owner=osowoso
          SYNC=$(ls ${sync}/)
          echo "$SYNC"
          echo 'group:' > .github/sync.yml
          echo '  - files:' >> .github/sync.yml
          for item in $SYNC; do
            echo "    - source: ${sync}/${item}" >> .github/sync.yml
            echo "      dest: $item" >> .github/sync.yml
          done
          echo '    repos: |' >> .github/sync.yml
          # Here use sync or syncD variable
          echo "      ${owner}/${syncD}@${branch}" >> .github/sync.yml

      - name: Distro SVG
        run: |
          sync=distro-svg
          branch=main
          owner=osowoso
          SYNC=$(ls ${sync}/)
          echo "$SYNC"
          echo '' >> .github/sync.yml
          echo '  - files:' >> .github/sync.yml
          for item in $SYNC; do
            echo "    - source: ${sync}/${item}" >> .github/sync.yml
            echo "      dest: $item" >> .github/sync.yml
          done
          echo '    repos: |' >> .github/sync.yml
          echo "      ${owner}/${sync}@${branch}" >> .github/sync.yml

      - name: oSoWoSo Site and GitHub profile
        run: |
          sync=github
          syncD=.github
          branch=main
          owner=osowoso
          SYNC=$(ls ${sync}/)
          echo "$SYNC"
          echo '' >> .github/sync.yml
          echo '  - files:' >> .github/sync.yml
          for item in $SYNC; do
            echo "    - source: ${sync}/${item}" >> .github/sync.yml
            echo "      dest: $item" >> .github/sync.yml
          done
          echo '    repos: |' >> .github/sync.yml
          echo "      ${owner}/${syncD}@${branch}" >> .github/sync.yml

      - name: Gumak
        run: |
          sync=gumak
          branch=main
          owner=osowoso
          SYNC=$(ls ${sync}/)
          echo "$SYNC"
          echo '' >> .github/sync.yml
          echo '  - files:' >> .github/sync.yml
          for item in $SYNC; do
            echo "    - source: ${sync}/${item}" >> .github/sync.yml
            echo "      dest: $item" >> .github/sync.yml
          done
          echo '    repos: |' >> .github/sync.yml
          echo "      ${owner}/${sync}@${branch}" >> .github/sync.yml

      - name: Quickemu
        run: |
          sync=quickemu
          branch=master-patched
          owner=osowoso
          SYNC=$(ls ${sync}/)
          echo "$SYNC"
          echo '' >> .github/sync.yml
          echo '  - files:' >> .github/sync.yml
          for item in $SYNC; do
            echo "    - source: ${sync}/${item}" >> .github/sync.yml
            echo "      dest: $item" >> .github/sync.yml
          done
          echo '    repos: |' >> .github/sync.yml
          echo "      ${owner}/${sync}@${branch}" >> .github/sync.yml

      - name: vbm
        run: |

          sync=vbm
          branch=vbm
          owner=osowoso
          SYNC=$(ls ${sync}/)
          echo "$SYNC"
          echo '' >> .github/sync.yml
          echo '  - files:' >> .github/sync.yml
          for item in $SYNC; do
            echo "    - source: ${sync}/${item}" >> .github/sync.yml
            echo "      dest: $item" >> .github/sync.yml
          done
          echo '    repos: |' >> .github/sync.yml
          echo "      ${owner}/${sync}@${branch}" >> .github/sync.yml

      - name: Void Helper (post-installation script)
        run: |
          sync=void-helper
          branch=master
          owner=osowoso
          SYNC=$(ls ${sync}/)
          echo "$SYNC"
          echo '' >> .github/sync.yml
          echo '  - files:' >> .github/sync.yml
          for item in $SYNC; do
            echo "    - source: ${sync}/${item}" >> .github/sync.yml
            echo "      dest: $item" >> .github/sync.yml
          done
          echo '    repos: |' >> .github/sync.yml
          echo "      ${owner}/${sync}@${branch}" >> .github/sync.yml

      - name: Void Wallpapers
        run: |
          sync=wallpapers
          syncD=Void-Wallpapers
          branch=main
          owner=osowoso
          SYNC=$(ls ${sync}/)
          echo "$SYNC"
          echo '' >> .github/sync.yml
          echo '  - files:' >> .github/sync.yml
          for item in $SYNC; do
            echo "    - source: ${sync}/${item}" >> .github/sync.yml
            echo "      dest: $item" >> .github/sync.yml
          done
          echo '    repos: |' >> .github/sync.yml
          echo "      ${owner}/${syncD}@${branch}" >> .github/sync.yml

      - name: push
        run: |
          git config --global user.name web-flow
          git config --global user.email "noreply@github.com"
          git add .github/sync.yml
          git commit -m "Create sync.yml" || echo "Nothing to commit"
          git push || echo "Nothing to push"
          cat .github/sync.yml >> $GITHUB_STEP_SUMMARY

      - name: 🛰️ Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.TOKEN }}
          BRANCH_PREFIX: ''
          SKIP_PR: true
          ORIGINAL_MESSAGE: true
