name: Create sync.yml
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
      - name: prepare
        run: |
          #VOID=$(curl https://api.github.com/repos/void-linux/void-packages/contents | jq -r '.[] | "\(.name) (\(.type))"' | cut -d' ' -f1)
          TEST=$(ls TEST/)
          echo "$TEST"
          echo 'group:' > .github/sync.yml
          echo '  - files:'
          
          for item in $VOID; do
            echo "    - $item" >> .github/sync.yml
            #echo "  - source: ../$item" >> .github/sync.yml
            #echo "    dest: ./$item" >> .github/sync.yml
          done

      - name: push
        run: |
          git config --global user.name web-flow
          git config --global user.email "noreply@github.com"
          git add .github/sync.yml
          git commit -m "Create sync.yml"
          git push
          cat .github/sync.yml >> $GITHUB_STEP_SUMMARY
